# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Enable version updates for VSCode devcontainers
   - package-ecosystem: "devcontainers"
   directory: "/"
   schedule:
     interval: weekly

  # Enable version updates for python
  - package-ecosystem: "pip"
    # Look for a `requirements` in the `root` directory
    directory: "/requirements"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Labels on pull requests for version updates only
    labels: ["ci/cd"]
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"
    # Allow up to 5 open pull requests for pip dependencies
    open-pull-requests-limit: 5
    reviewers:
      - "Lightning-AI/core-bolts"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Labels on pull requests for version updates only
    labels: ["ci/cd"]
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"
    # Allow up to 5 open pull requests for GitHub Actions
    open-pull-requests-limit: 5
    reviewers:
      - "Lightning-AI/core-bolts"
